
# 1.Створити змінні базових (atomic) типів. Базові типи: character, numeric, integer, complex, logical.

x<-'character'
y<-1
f<-1L
k<-1 + 5i
m<-TRUE

# 2.Створити вектори, які: містить послідовність з 5 до 75; містить числа 3.14, 2.71, 0, 13; 100 значень TRUE.

x<-c(5:75)
y<-c(3.14, 2.71, 0, 13)
f<-replicate(100, c(TRUE))

# 3.Створити наступну матрицю за допомогою matrix, та за допомогою cbind або rbind

matrix(c(0.5, 3.9, 0, 2, 1.3, 131, 2.2, 7, 3.5, 2.8, 4.6, 5.1), ncol=3, nrow=4)


col1<-c(0.5, 3.9, 0, 2)
col2<-c(1.3, 131, 2.2, 7)
col3<-c(3.5, 2.8, 4.6, 5.1)
combined_matrix<-cbind(col1, col2, col3)
combined_matrix


# 4.Створити довільний список (list), в який включити всі базові типи.

list('character', 1, 1L, 1 + 5i, TRUE)

# 5.Створити фактор з трьома рівнями «baby», «child», «adult».

people<-c('baby', 'child', 'adult')
factor(people, levels=c('baby','child','adult'))

# 6.Знайти індекс першого значення NA в векторі 1, 2, 3, 4, NA, 6, 7, NA, 9, NA, 11. Знайти кількість значень NA.

match(NA, c(1, 2, 3, 4, NA, 6, 7, NA, 9, NA, 11))

sum(is.na(c(1, 2, 3, 4, NA, 6, 7, NA, 9, NA, 11)))

# 7.Створити довільний data frame та вивести в консоль.

data_frame<-data.frame(number = c(1,2,3,4),letter = c('x','y','f','k'))
data_frame

# 8.Змінити імена стовпців цього data frame.

colnames(data_frame)<-c('nmbr', 'ltr')
data_frame



