

# 1.Функція add2(x, y), яка повертає суму двох чисел.

add2<- function(x,y) {
    return(x + y)
}
add2(2,4)

# 2.Функція above(x, n), яка приймає вектор та число n, та повертає всі елементі вектору, які більше n. По замовчуванню n = 10.

above<- function(v,n=10){
    return(v[v > n])
}
above(c(1,2,8,9,100,1000,1002,1004))


# 3.Функція my_ifelse(x, exp, n), яка приймає вектор x, порівнює всі його елементи за допомогою exp з n, та повертає елементи вектору, які відповідають умові expression. Наприклад, my_ifelse(x, “>”, 0) повертає всі елементи x, які більші 0. Exp може дорівнювати “<”, “>”, “<=”, “>=”, “==”. Якщо exp не співпадає ні з одним з цих виразів, повертається вектор x.

my_ifelse<- function(x,exp,n){if (exp == "<")
      {return(x[x<n])}
     else if (exp==">")
     {return(x[x>n])}
     else if (exp=="<=")
     {return(x[x<=n])}
     else if (exp==">=")
     {return(x[x>=n])}
     else if (exp=="==")
     {return(x[x==n])}
     else x}

x <- c(1,2,3,4,5,6,7,8,9,10)
my_ifelse(x,">",0)


# 4.Функція columnmean(x, removeNA), яка розраховує середнє значення (mean) по кожному стовпцю матриці, або data frame. Логічний параметр removeNA вказує, чи видаляти NA значення. По замовчуванню він дорівнює TRUE.

columnmean <- function(x, removeNA = TRUE) 

  {return(colMeans(x, na.rm = removeNA))}

columnmean(matrix(c(7, 11, NA, 18, 9, NA, NA, 14, 2), nrow = 9, ncol = 4))

x <- data.frame(x = 3:4, y = 8:9, f = 5:6)
columnmean(x)
